name: Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Vulnerability Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: integration_tests
    
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Run integration tests
        run: |
          set -e
          docker compose -f docker-compose.yml up --quiet-pull  -d
          sleep 5
          go test -v -tags=integration ./...

      - name: Tear down environment
        if: always()
        run: |
          set -e
          docker compose -f docker-compose.yml down
